# Generated by Django 2.2.12 on 2020-04-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_committee_member',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MaintenanceTxns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Users')),
            ],
            options={
                'db_table': 'maintenance_txns',
            },
        ),
    ]
