# Generated by Django 2.2.12 on 2020-04-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200421_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
    ]
